__title__ = 'async-vk-bot'
__version__ = '0.6.2'
__description__ = 'Async VK bot builder'
__url__ = 'https://github.com/Suenweek/async-vk-bot'
__author__ = 'Roman Novatorov'
__author_email__ = 'roman.novatorov@gmail.com'
